source 'https://github.com/morapelker/tedooo-pod-repo.git'

source 'https://cdn.cocoapods.org/'
use_frameworks!

target 'TedoooCategories_Tests' do
  pod 'TedoooCategories', :path => '../'
  
  pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
end
